[package]
name = "jasp"
version = "0.1.0"
authors = ["Joni Katajamäki <joni.katajamaki@wunderdog.fi>"]
edition = "2018"

[dependencies]
ordered-float = "2.5.1"
pest = "2.1.3"
pest_consume = "1.1.0"
pest_derive = "2.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"